version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8.9.54-alpine
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: chat
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://clickhouse:8123/ping || exit 1
      interval: 5s
      timeout: 3s
      retries: 100

  collector:
    image: ghcr.io/openmeterio/benthos-openmeter
    command: benthos -c /etc/benthos/config.yaml
    restart: always
    depends_on:
      clickhouse:
        condition: service_healthy
    env_file:
      - .env
    environment:
      CLICKHOUSE_DSN: clickhouse://default:default@clickhouse:9000/chat?dial_timeout=200ms&max_execution_time=60
    volumes:
      - ./config.yaml:/etc/benthos/config.yaml:ro

  seeder:
    image: ghcr.io/openmeterio/benthos-openmeter
    command: benthos -c /etc/benthos/config.yaml
    restart: always
    depends_on:
      clickhouse:
        condition: service_healthy
    environment:
      OPENMETER_URL: http://forwarder:4196
      CLICKHOUSE_DSN: clickhouse://default:default@clickhouse:9000/chat?dial_timeout=200ms&max_execution_time=60
    volumes:
      - ./seed/config.yaml:/etc/benthos/config.yaml:ro
